### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Grumrick** [maoschanz/notes-extension-gnome#13]
In Ubuntu 18.04 LTS I am only able to  add text when in Above Everything display. Is this the way it is meant to be?
Could the Menu Bar and Icons be reduced in size and the Sticky made easier to move?
Other than these issues, the extension is a good and useful one but not as easy to use as one I used in Ubuntu 16.04 LTS.
Cheers,
Grum

**Comment by Maestroschan** [comment]
>In Ubuntu 18.04 LTS I am only able to add text when in Above Everything display. Is this the way it is meant to be?

This is meant to be used in GNOME Shell, which, by default, doesn't open a unclosable transparent nautilus windows above the desktop.

>the Sticky made easier to move?

They are hard to move only when there is a window behind them: only when there is the "above all" setting. I'm not even sure it's technically possible to fix it but i'll let the issue open, maybe i'll have an idea
