### ISSUE TITLE
Replacement of the "above all" layer

### ISSUE THREAD

**Issue by maoschanz** [maoschanz/notes-extension-gnome#15]
## Current situation

notes are above windows, but are tracked individually

(+) the user can still interact with windows

(-) notes can't be moved (issue #13)

## Wanted behavior

notes are on a specific layer, which is tracked too

(-) the user can't interact with windows, this needs to be explicited by a dark thing like when doing alt+f2

(+) notes can be moved

**Comment by Maestroschan** [comment]
todo: disconnect some signals and destroy the widget

also, i should check how bad it looks with multiple monitors

**Comment by maoschanz** [comment]
abandoned idea
