### ISSUE TITLE
Multi monitor support

### ISSUE THREAD

**Issue by maoschanz** [maoschanz/notes-extension-gnome#2]
maybe later

**Comment by amivaleo** [comment]
Any news about this? Because notes do not work perfectly when other monitors are plugged in... :(

**Comment by maoschanz** [comment]
No because i don't have a second monitor to test it. How bad does it look ?

**Comment by amivaleo** [comment]
If you set "Above everything" and you have an external monitor, the background of THAT monitor fades and gets darker, but your notes appear on the other monitor (which is the primary monitor).
And that's not all.
All the open windows on the primary monitor do not lose focus, so you can interact with them and your notes that should be on a different 'level' (well... They should be "above everything"!).
If you want to hide your notes, you can click the icon on gnome panel OR you have to click on the faded background of the external monitor!

I added a screenshot: the bottom desktop is the primary monitor.
![schermata da 2018-11-14 10-16-09](https://user-images.githubusercontent.com/24316547/48472333-5ba04000-e7f6-11e8-8a8f-fbda685fdaf2.png)
