### ISSUE TITLE
Toggle button that switches between the 3 possible states/layers

### ISSUE THREAD

**Issue by Vladislavuz** [maoschanz/notes-extension-gnome#29]
Please add a click on the tray icon to display notes on top of all windows.

**Comment by maoschanz** [comment]
This already how the extension works

**Comment by vladislavyuzbekov** [comment]
> This already how the extension works

The extension works like this only in mode "adove everything". In the "on background" mode it is impossible to do this and you have to minimize the windows.

**Comment by vladislavyuzbekov** [comment]
> > This already how the extension works
> 
> The extension works like this only in mode "adove everything". In the "on background" mode it is impossible to do this and you have to minimize the windows.

i mean ubuntu 19.04

**Comment by maoschanz** [comment]
Yes if you want the notes to be above windows they'll be above windows, and if you don't they will not.

**Comment by maoschanz** [comment]
Sorry i didn't understand *at all* what you meant but i think i've got it: the idea would be to always keep the notes visible, and clicking on the icon would toggle their position: a click would either send them in the background or in the foreground.
