### ISSUE TITLE
Cool animations

### ISSUE THREAD

**Issue by maoschanz** [maoschanz/notes-extension-gnome#3]
- [ ] when new note
- [ ] when deleting a note
- [x] when moving notes
- [x] when resizing notes

**Comment by Maestroschan** [comment]
The deleting animation is working but commented, i'll wait for 3.28's source code since i'm not sure wtf they are doing with tweener and its numerous errors https://bugzilla.gnome.org/show_bug.cgi?id=791233

**Comment by maoschanz** [comment]
abandoned idea
