### ISSUE TITLE
Gnome 3.34 Error

### ISSUE THREAD

**Issue by Befo** [maoschanz/notes-extension-gnome#32]
Looking Glass says: "GrabHelper owner must be a Clutter.Actor" in GNOME 3.34,

**Comment by noccy80** [comment]
Having the same issue with the same error since upgrading from Ubuntu 19.04 to 19.10

**Comment by maoschanz** [comment]
mutter's regression mentionned in the referenced commit haven't disappear 

>	//FIXME according to common sense, clicking in an entry should give it
		//the keyboard focus, and it was how it worked before GS 3.33, but after
		//3.33 there is an error if i don't manage the grab manually. The error:
		//clutter_input_focus_set_input_panel_state: assertion 'clutter_input_focus_is_focused (focus)' failed
		//Managing the grab manually is only a very shitty workaround, since
		//the auto_focus can work but the defaut behavior (focus the entry
		//when the user decide to focus the entry) can't work because the
		//button-press-event signal is sent only when the user clicks where
		//there is no text, making the entries unsuitable for use by normal
		//humans. 

I can't fix the damn window manager
