### ISSUE TITLE
Not Working for Gnome 3.34.4 at Fedora 31

### ISSUE THREAD

**Issue by adrianoduque97** [maoschanz/notes-extension-gnome#35]
It marks an error when installed the extension

**Comment by maoschanz** [comment]
It might be related to the fact it's not a version of GNOME Shell supported by this extension ![image](https://user-images.githubusercontent.com/19996113/75634231-25b1e580-5c0c-11ea-8545-39bcbba6c7ac.png)
as explained in #32

**Comment by maoschanz** [comment]
to be fair you can install it manually from this github repo, but some options will be broken
