### ISSUE TITLE
Limited focus-area size?

### ISSUE THREAD

**Issue by autonum** [maoschanz/notes-extension-gnome#36]
Hello.
(On debian-gnome)

It seems that the area of the note over which the arrow gets the focus – and thus the cursor – on the note does not always cover the whole note.
Therefore, when hovering over that left-over area, the focus does not happen.
In the picture here attached, one can see the grey zone where the focus does not occur.
This zone correspond to the area exceeding the note window's size.

Would it be possible to make it so the focus occurs on the whole area of the note, not matter the size of the window?

![«Grey» (no focus) zone on note exceeding window size ](https://user-images.githubusercontent.com/62657912/77556331-ac2eaf80-6eb8-11ea-969c-c2439cd77794.png)

**Comment by maoschanz** [comment]
that's GNOME Shell's widgets: don't get the focus when you click on it, aren't rendered correctly if they're in a scrollable area. Amazing. Great framework.

to be honest it could be worse: i'm pretty sure that, if i tried to update the extension to modern GS versions, notes like your example would get focus if you hover/click upon the part of the entry which isn't visible
