### ISSUE TITLE
Can't delete notes on Wayland

### ISSUE THREAD

**Issue by adrianoduque97** [maoschanz/notes-extension-gnome#45]
When trying to delete a note on Gnome 3.36.3 Wayland on Fedora 32 the note don't got deleted

**Comment by maoschanz** [comment]
please run `journalctl -f /usr/bin/gnome-shell` (with sudo if necessary), reproduce the issue and tell what the error is

**Comment by adrianoduque97** [comment]
Just ran the shell command and reproduce the action several times

![Notes_Big](https://user-images.githubusercontent.com/47148409/85229457-65652e80-b3af-11ea-9910-64088e1a43a8.png)

**Comment by maoschanz** [comment]
You should use a version of the extension that is compatible with your version of GNOME Shell

**Comment by maoschanz** [comment]
You're using a version so old i don't even find which one it is... next time please provide this info directly in the bug report

(marked as duplicate because it's the 2nd point of issue #39)
