### ISSUE TITLE
can't activate "on the background" note

### ISSUE THREAD

**Issue by themighty1** [maoschanz/notes-extension-gnome#64]
Thank you for this extension. I really like how it can stay on the desktop when all other applications are minimized.
Currently in order to modify my "on the background" notes, I do the following
1. fire up Extension
2. press settings cogwheel for Notes
3. switch to "above everything"
4. modify the note
5. switch back to "on the background"

Is this the quickest way to do editing of "on the background" notes.
If so, it would be very helpful to have a shortcut to quickly switch between "on the background" and "above everything" modes.

Once again, thank you for the effort to keep this extension working despite the ever-changing gnome shell API.

**Comment by maoschanz** [comment]
thank you for your suggestion, but i'll close this discussion because it's already the idea of issue #29 (which i'll probably implement this spring)
