### ISSUE TITLE
Notes don't appear after clicking pen icon in toolbar

### ISSUE THREAD

**Issue by scottwn** [maoschanz/notes-extension-gnome#69]
Hi, I have loved Notes for a while and it's been among my must have extensions; sadly today the notes won't open for me at all. I checked looking glass which showed no Notes errors; `sudo journalctl /usr/bin/gnome-shell | grep -i notes` is also empty.

**Comment by maoschanz** [comment]
what's the version of GNOME Shell you're using?

meanwhile, you may want to go to `~/.local/share` to find the directory with all your notes, and make a backup

**Comment by scottwn** [comment]
`GNOME Shell 3.32.2`

**Comment by maoschanz** [comment]
wow that's pretty old, and what's the version of the extension? (visible in the "about" tab of the preferences)

**Comment by scottwn** [comment]
Extension version 18

**Comment by scottwn** [comment]
I'm on the latest version of RHEL, 8.4; GNOME shell 3.32.2 is the default version for the OS https://distrowatch.com/table.php?distribution=redhat

**Comment by maoschanz** [comment]
weird, the version should be compatible...

once you've done a backup of your notes, you can try to delete the directory and restart GNOME Shell, it should reset entirely the extension and clicking on the icon should then create an initial new empty sticky note

**Comment by scottwn** [comment]
that worked, thank you
