### ISSUE TITLE
Installation From here not working

### ISSUE THREAD

**Issue by orschiro** [maoschanz/notes-extension-gnome#7]
Getting a page not found. :-(

![image](https://user-images.githubusercontent.com/170947/40300190-ccc5bed4-5ce8-11e8-9b3f-2bf6884ad3f1.png)

**Comment by Maestroschan** [comment]
Yes i wrote the readme prematurely, before the extension approval. And the extension has still not been approved.

**Comment by orschiro** [comment]
I see. What a bummer! :-( 

They could need some more volunteers reviewing extensions, I guess.
