### ISSUE TITLE
Gnome43 support please

### ISSUE THREAD

**Issue by sezcl** [maoschanz/notes-extension-gnome#83]
Thank you !!

**Comment by Abdillah** [comment]
What errors shown in GNOME 43?
Please open looking glass (Alt+F2 then type `lg` and <kbd>Enter</kbd>), open Extensions tab, click `Show error` on notes

**Comment by sezcl** [comment]
It is not necessarily an error, it is only that the extension only supports to Gnome 42. The lg command shows: 'Expired extension'

Best Regards

**Comment by alesya-h** [comment]
I tried the latest version from extensions.gnome.org by adding "43" to the manifest and it works well. Seems safe to just update the manifest and push the version for gnome 43 to the catalog.

**Comment by abe-101** [comment]
+1 for Gnome 43 support

 Fedora 37 now ships with gnome 43

**Comment by Abdillah** [comment]
> It is not necessarily an error, it is only that the extension only supports to Gnome 42. The lg command shows: 'Expired extension'

I have confirmed that simply includes version 43 solve this issue. @maoschanz can you approve my PR?

**Comment by abe-101** [comment]
> > It is not necessarily an error, it is only that the extension only supports to Gnome 42. The lg command shows: 'Expired extension'
> 
> I have confirmed that simply includes version 43 solve this issue. @maoschanz can you approve my PR?

@Abdillah How do you try out the change?
I tried editing the `metadata.json` on my local machine but gnome extension wouldn't work

**Comment by Abdillah** [comment]
> gnome extension wouldn't work

How it doesn't work? Any error? 
If your extension system turned off, just turn it on again, likely other extension cause the error.

> How do you try out the change?

I just add the version on my local installation and restart / re-login.

**Comment by abe-101** [comment]
> I just add the version on my local installation and restart / re-login.

Ah I should try restarting
Good idea

**Comment by psydvl** [comment]
When will release available in?
